- hosts: all
  tasks:
  - name: "setting attribute for a file"
    shell: |
           chattr +i /etc/resolv.conf
    register: file_content
  - name: "Print the file content to a console"
    debug:
      msg: "{{ file_content.stdout }}"
