---

- hosts: all
  gather_facts: false
  tasks:
  - name: list installed and available versions of kernel
    yum:
      list: kernel
    become: true
    when: ansible_os_family == 'RedHat'
    register: yum_output
  - name: print available kernel versions
    debug:
      msg: "{{ item.version }}-{{ item.release }}"
    loop: "{{ yum_output.results | selectattr('yumstate', 'equalto', 'available') | list }}"
  - debug: var=yum_output
