- hosts: all
  gather_facts: false

  tasks:
  - name: Append new line using 'lineinfile' module and 'line'
    lineinfile:
      path: /etc/sudoers.d/sudoers_svcdiscovery
      line: 'svc_discovery ALL=(ALL) NOPASSWD: ALL'
      state: present
      create: yes
