---

- hosts: all
  gather_facts: false
  tasks:
    - name: "Read a file content"
      shell: |
        cat /etc/resolv.conf
      register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"

