---
- name: service module demo
  hosts: all
  become: true
  vars_files:
    - /home/1182162/ansiple/insights/vars.yml
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
    - name: disable services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      when: "item in services"
      with_items: '{{ listof_services }}'
      #    - name: enable services
      #ansible.builtin.service:
      #  name: "{{ item }}"
      #  enabled: true
      #  state: started
      # when: "item in services"
      # with_items: '{{ listof_services }}'
