---
- name: uimagent and sysedge agent removal
  hosts: all
  tasks:
    - name: Stopping nimbus service on RHEL 6
      service:
        name: nimbus
        state: stopped
      become: yes
      when: >
        (ansible_facts['distribution'] == "RedHat"
        and ansible_facts['distribution_major_version'] == "6")
      ignore_errors: yes

    - name: Stopping nimbus service on RHEL 7&8
      ansible.builtin.systemd:
        name: nimbus
        state: stopped
      become: yes
      when: >
        ((ansible_facts['distribution'] == "RedHat"
        and ansible_facts['distribution_major_version'] == "7")
        or
        (ansible_facts['distribution'] == "RedHat"
        and ansible_facts['distribution_major_version'] == "8"))
      ignore_errors: yes

    - name: Remove uimagent RPM in RHEL 6&7
      yum:
        name: uimagent
        state: absent
      become: yes
      when: >
        ((ansible_facts['distribution'] == "RedHat"
        and ansible_facts['distribution_major_version'] == "6")
        or
        (ansible_facts['distribution'] == "RedHat"
        and ansible_facts['distribution_major_version'] == "7"))

    - name: Remove nimsoft RPM in RHEL8
      dnf:
        name: 
          - nimsoft-robot
          - uimagent
        state: absent
      become: yes
      when: >
        (ansible_facts['distribution'] == "RedHat"
        and ansible_facts['distribution_major_version'] == "8")
